#!/usr/bin/env python3
"""Generate Prometheus scrape config for PI-01 local development."""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

SCRAPE_TARGETS = [
    "api-gateway:8080",
    "auth-service:8001",
    "rbac-service:8002",
    "orchestrator-service:8003",
    "workflow-engine:8004",
    "task-engine:8005",
    "approval-service:8006",
    "agent-runtime:8007",
    "agent-registry:8008",
    "model-router:8009",
    "tool-registry:8010",
    "memory-service:8011",
    "audit-service:8012",
    "secrets-service:8013",
    "policy-engine:8014",
    "config-service:8015",
]

CONFIG = """\
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: aep-platform-services
    metrics_path: /metrics
    static_configs:
      - targets:
{targets}
"""

HEADER = """\
# Generated by scripts/generate_prometheus_config.py — do not edit manually.
"""


def main() -> None:
    targets_block = "\n".join(f"          - {target}" for target in SCRAPE_TARGETS)
    content = HEADER + CONFIG.format(targets=targets_block)
    output = ROOT / "observability" / "prometheus" / "prometheus.yml"
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(content, encoding="utf-8")
    print(f"Wrote {output}")


if __name__ == "__main__":
    main()
